[package]
name = "rdbprt-reval"
version = "0.1.0"
authors = ["hos <hosodahajime@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding_rs = "0.8.26"
regex = "1.4.3"